name: Build apt for armhf only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arm32v7/debian:bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo "deb http://deb.debian.org/debian sid main" > /etc/apt/sources.list
          apt-get update

      - name: Install required packages
        run: |
          apt-get install -y --no-install-recommends \
            build-essential \
            dpkg-dev \
            cmake \
            ninja-build \
            curl \
            ca-certificates \
            git \
            pkg-config \
            gcc \
            g++ \
            libbz2-dev \
            libdb-dev \
            libssl-dev \
            liblz4-dev \
            liblzma-dev \
            libseccomp-dev \
            libsystemd-dev \
            libudev-dev \
            libxxhash-dev \
            libzstd-dev \
            zlib1g-dev

      - name: Download googletest (native armhf build)
        run: |
          curl -L https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz | tar xz
          mv googletest-release-1.12.1 googletest

      - name: Build googletest
        working-directory: ./googletest
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=OFF -G Ninja
          ninja
          cp lib/*.a /usr/lib/
          cp -r ../googletest/include /usr/include/gtest

      - name: Extract apt source
        run: |
          apt-get source apt
          cd apt-* && dpkg-buildpackage -us -uc -b
