name: Build APT Package (amd64 & armhf)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: Prepare working directory
        run: mkdir -p /home/runner/work/apt/apt

      - name: Add Ubuntu Repo (Fixed to Noble Numbat)
        run: |
          UBUNTU_CODENAME="noble"
          # amd64 컨테이너에서는 amd64 패키지만 가져오도록 명시
          echo "deb [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" > /etc/apt/sources.list
          echo "deb-src [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src [arch=amd64] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list

      - name: Install dependencies (apt, build-essential, etc)
        working-directory: /home/runner/work/apt/apt
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            dpkg-dev \
            devscripts \
            fakeroot \
            libssl-dev \
            libdb-dev \
            libbz2-dev \
            liblzma-dev \
            liblz4-dev \
            libzstd-dev \
            libudev-dev \
            libsystemd-dev \
            libseccomp-dev \
            libxxhash-dev \
            docbook-xml \
            docbook-xsl \
            xsltproc \
            graphviz \
            w3m \
            po4a \
            googletest \ 
            libgtest-dev \
            triehash \
            zlib1g-dev \
            doxygen

          # googletest 준비
          cd /usr/src
          git clone --depth 1 --branch release-1.14.0 https://github.com/google/googletest.git
          cd googletest && cmake -B build && cmake --build build
          cp -r googletest include /usr

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/apt/apt

      - name: Patch APT source
        run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh

      - name: Build (amd64)
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg-buildpackage -us -uc -b

  build-armhf:
    runs-on: ubuntu-latest # AMD64 런너 그대로 사용
    container:
      image: arm32v7/ubuntu:24.04 # arm32v7 이미지
    steps:
      - name: Set up QEMU # <-- 이 스텝 추가! AMD64에서 ARM 에뮬레이션 활성화
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Prepare working directory
        run: mkdir -p /home/runner/work/apt/apt

      - name: Add Ubuntu Repo (Fixed to Noble Numbat)
        run: |
          UBUNTU_CODENAME="noble"
          # armhf 컨테이너이므로 armhf 패키지만 가져오도록 명시 (이제 QEMU 덕분에 가능)
          echo "deb [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" > /etc/apt/sources.list
          echo "deb-src [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src [arch=armhf] http://kr.archive.ubuntu.com/ubuntu/ ${UBTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
        
      - name: Install dependencies (apt, build-essential, etc)
        working-directory: /home/runner/work/apt/apt
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            devscripts \
            fakeroot \
            dpkg-dev \
            libssl-dev \
            libdb-dev \
            libbz2-dev \
            liblzma-dev \
            liblz4-dev \
            libzstd-dev \
            libudev-dev \
            libsystemd-dev \
            libseccomp-dev \
            libxxhash-dev \
            docbook-xml \
            docbook-xsl \
            xsltproc \
            graphviz \
            w3m \
            po4a \
            googletest \ 
            libgtest-dev \
            triehash \
            zlib1g-dev \
            doxygen

          # googletest 준비
          cd /usr/src
          git clone --depth 1 --branch release-1.14.0 https://github.com/google/googletest.git
          cd googletest && cmake -B build && cmake --build build
          cp -r googletest include /usr

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/apt/apt

      - name: Patch APT source
        run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh

      - name: Build (armhf)
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg-buildpackage -us -uc -b -aarmhf
