name: Build APT Package (amd64 & armhf)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: Prepare working directory
        run: mkdir -p /home/runner/work/apt/apt

      - name: Add Ubuntu Repo (Fixed to Noble Numbat)
        run: |
          UBUNTU_CODENAME="noble"
          echo "deb http://archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" > /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
        
      - name: Verify sources.list content
        run: cat /etc/apt/sources.list

      - name: Install cross toolchain & deps
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg --add-architecture amd64
          apt-get update
          echo "--- apt-cache search crossbuild-essential-armhf results ---"
          apt-cache search crossbuild-essential-armhf # crossbuild-essential-armhf 검색 결과 확인
          echo "---------------------------------------------------------"
          apt-get install -y \
            crossbuild-essential-armhf \
            cmake \
            ninja-build \
            pkg-config \
            devscripts \
            fakeroot \
            dpkg-dev \
            libssl-dev:armhf \
            libdb-dev:armhf \
            libbz2-dev:armhf \
            liblzma-dev:armhf \
            liblz4-dev:armhf \
            libzstd-dev:armhf \
            libudev-dev:armhf \
            libsystemd-dev:armhf \
            libseccomp-dev:armhf \
            libxxhash-dev:armhf \
            docbook-xml \
            docbook-xsl \
            xsltproc \
            graphviz \
            w3m \
            po4a \
            googletest \ 
            libgtest-dev \
            triehash \
            zlib1g-dev \
            doxygen


          # googletest 준비
          cd /usr/src
          git clone --depth 1 --branch release-1.14.0 https://github.com/google/googletest.git
          cd googletest && cmake -B build && cmake --build build
          cp -r googletest include /usr

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/apt/apt

      - name: Patch APT source
        run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh

      - name: Build (amd64)
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg-buildpackage -us -uc -b

  build-armhf:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: Prepare working directory
        run: mkdir -p /home/runner/work/apt/apt

      - name: Add Ubuntu Repo (Fixed to Noble Numbat)
        run: |
          UBUNTU_CODENAME="noble"
          echo "deb http://archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" > /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ $UBUNTU_CODENAME main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${UBUNTU_CODENAME}-proposed main restricted universe multiverse" >> /etc/apt/sources.list
        
      - name: Verify sources.list content
        run: cat /etc/apt/sources.list

      - name: Install cross toolchain & deps
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg --add-architecture armhf
          apt-get update
          echo "--- apt-cache search crossbuild-essential-armhf results ---"
          apt-cache search crossbuild-essential-armhf # crossbuild-essential-armhf 검색 결과 확인
          echo "---------------------------------------------------------"
          apt-get install -y \
            crossbuild-essential-armhf \
            cmake \
            ninja-build \
            pkg-config \
            devscripts \
            fakeroot \
            dpkg-dev \
            libssl-dev:armhf \
            libdb-dev:armhf \
            libbz2-dev:armhf \
            liblzma-dev:armhf \
            liblz4-dev:armhf \
            libzstd-dev:armhf \
            libudev-dev:armhf \
            libsystemd-dev:armhf \
            libseccomp-dev:armhf \
            libxxhash-dev:armhf \
            docbook-xml \
            docbook-xsl \
            xsltproc \
            graphviz \
            w3m \
            po4a \
            googletest \ 
            libgtest-dev \
            triehash \
            zlib1g-dev \
            doxygen


          # googletest 준비
          cd /usr/src
          git clone --depth 1 --branch release-1.14.0 https://github.com/google/googletest.git
          cd googletest && cmake -B build && cmake --build build
          cp -r googletest include /usr

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/apt/apt

      - name: Patch APT source
        run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh

      - name: Build (armhf)
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg-buildpackage -us -uc -b -aarmhf
