name: Build & Release Custom APT

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { arch: [armhf, amd64] }
    container: debian:bookworm
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3

      # 1. 최신 apt 버전 GitHub API에서 받아오기 (Debian apt repo)
      - name: Get latest apt version
        id: get_version
        run: |
          curl -s https://api.github.com/repos/Debian/apt/releases/latest | jq -r .tag_name | sed 's/^v//' > latest_version.txt
          echo "APT_VERSION=$(cat latest_version.txt)" >> $GITHUB_ENV

      - name: Install latest dpkg-dev from Debian sid
        run: |
          set -e
          # 최신 버전 검색
          LATEST_URL=$(curl -s http://ftp.debian.org/debian/pool/main/d/dpkg/ \
            | grep -oP 'dpkg-dev_[0-9]+\.[0-9]+\.[0-9]+_all\.deb' \
            | sort -V | tail -n1)

          echo "Downloading $LATEST_URL"
          wget http://ftp.debian.org/debian/pool/main/d/dpkg/$LATEST_URL
          apt-get install -y ./$(basename "$LATEST_URL")


      - run: |
          apt-get update
          apt-get install -y \
          build-essential devscripts fakeroot qemu-user-static curl jq \
          libzstd-dev \
          cmake docbook-xml docbook-xsl googletest libbz2-dev libdb-dev libssl-dev \
          liblz4-dev liblzma-dev libseccomp-dev libsystemd-dev libudev-dev libxxhash-dev \
          ninja-build pkg-config po4a triehash xsltproc zlib1g-dev doxygen graphviz w3m

      - run: |
          echo 'Acquire::AllowInsecureRepositories "true"; APT::Get::AllowUnauthenticated "true";' | tee /etc/apt/apt.conf.d/99insecure

      - run: |
          echo "deb-src http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb-src http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse" >> /etc/apt/sources.list

      - run: apt-get update && apt-get source apt=${{ env.APT_VERSION }}

      - run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh
      - env:
          DEB_BUILD_OPTIONS: nocheck
        run: |
          mkdir -p apt-${{ env.APT_VERSION }}
          echo -e "Package: apt\nPin: version ${{ env.APT_VERSION }}*\nPin-Priority: 1001" > apt-${{ env.APT_VERSION }}/preferences

      - env:
          DEB_BUILD_OPTIONS: nocheck
        run: dpkg-buildpackage -us -uc -b -a${{ matrix.arch }} --host-arch=${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: custom-apt-${{ matrix.arch }}
          path: ../apt_${{ env.APT_VERSION }}*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: custom-apt-armhf
          path: armhf

      - uses: actions/download-artifact@v4
        with:
          name: custom-apt-amd64
          path: amd64

      - uses: actions/create-release@v1
        with:
          tag_name: custom-apt-${{ env.APT_VERSION }}
          release_name: Custom APT ${{ env.APT_VERSION }}

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            armhf/apt_${{ env.APT_VERSION }}*.deb
            amd64/apt_${{ env.APT_VERSION }}*.deb
