name: Build APT Package (amd64 & armhf)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Prepare working directory
        run: mkdir -p /home/runner/work/apt/apt

      - name: Install dependencies (apt, build-essential, etc)
        working-directory: /home/runner/work/apt/apt
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            dpkg-dev \
            devscripts \
            fakeroot \
            libssl-dev \
            libdb-dev \
            libbz2-dev \
            liblzma-dev \
            liblz4-dev \
            libzstd-dev \
            libudev-dev \
            libsystemd-dev \
            libseccomp-dev \
            libxxhash-dev \
            docbook-xml \
            docbook-xsl \
            xsltproc \
            graphviz \
            w3m \
            po4a \
            googletest \
            libgtest-dev \
            triehash \
            zlib1g-dev \
            doxygen

          # googletest 준비
          cd /usr/src
          rm -rf googletest
          git clone --depth 1 --branch release-1.14.0 https://github.com/google/googletest.git
          cd googletest && cmake -B build && cmake --build build
          cp -r googletest include /usr

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/apt/apt

      - name: Patch APT source # <-- 이 스텝 추가!
        run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh

      - name: Build (amd64)
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg-buildpackage -us -uc -b

  build-armhf:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Prepare working directory
        run: mkdir -p /home/runner/work/apt/apt

      - name: Install cross toolchain & deps
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg --add-architecture armhf
          apt-get update
          apt-get install -y \
            crossbuild-essential-armhf \
            cmake \
            ninja-build \
            pkg-config \
            devscripts \
            fakeroot \
            dpkg-dev \
            libssl-dev:armhf \
            libdb-dev:armhf \
            libbz2-dev:armhf \
            liblzma-dev:armhf \
            liblz4-dev:armhf \
            libzstd-dev:armhf \
            libudev-dev:armhf \
            libsystemd-dev:armhf \
            libseccomp-dev:armhf \
            libxxhash-dev:armhf \
            docbook-xml \
            docbook-xsl \
            xsltproc \
            graphviz \
            w3m \
            po4a \
            googletest \
            libgtest-dev \
            triehash \
            zlib1g-dev \
            doxygen

          # googletest 준비
          cd /usr/src
          rm -rf googletest
          git clone --depth 1 --branch release-1.14.0 https://github.com/google/googletest.git
          cd googletest && cmake -B build && cmake --build build
          cp -r googletest include /usr

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/apt/apt

      - name: Patch APT source # <-- 이 스텝 추가!
        run: |
          chmod +x patches/patcher.sh
          ./patches/patcher.sh

      - name: Build (armhf)
        working-directory: /home/runner/work/apt/apt
        run: |
          dpkg-buildpackage -us -uc -b -aarmhf
